PROG = prog
OBJS = cal_main.o add.o sub.o mul.o dur.o
SRCS = $(OBJS:.o=.c)
DEPS = $(OBJS:.o=.d)
CFLAGS = -I. -Wall

.SUFFIXES: .d

$(PROG): $(OBJS)
	$(CC) -o $(PROG) $(OBJS)

.c.d:
	$(CC) -MM -o $@ $(CFLAGS) $<

clean:
	rm -rf $(PROG) $(OBJS) $(DEPS)

include $(DEPS)

.PHONY: dep clean
